### ISSUE TITLE
Some site components cannot be translated

### ISSUE THREAD

**Issue by R33D3M33R** [bdoin/GCompris-site#12]
Hello. Some site components cannot be translated. The problematic lines are highlighted in the following links:

https://github.com/bdoin/GCompris-site/blob/3dd84a0e7fec610ab7c53c758a97ca60cf9545b1/template/index.html#L67
https://github.com/bdoin/GCompris-site/blob/3dd84a0e7fec610ab7c53c758a97ca60cf9545b1/template/base.html#L94-L98

**Comment by bdoin** [comment]
Hi, thanks for your feddback. The github repo is no more the reference and the GitHub mirror is not updated. One of the error is already fixed. Are you interested in providing a translation?

**Comment by R33D3M33R** [comment]
Sure, but since I cannot commit to the KDE repository, here are the changes:
===================================================================
--- locale/sl.po	(revision aea93dac55b623d4fce2510a6aad7d5d43118075)
+++ locale/sl.po	(revision 241932b4ce575e587541eb4b6b5a35dfb15df9ff)
@@ -127,7 +127,7 @@
 
 #: template/index.html:88
 msgid "Other"
-msgstr ""
+msgstr "Drugo"
 
 #: template/index.html:162
 msgid "View all screenshots"
===================================================================
Btw: it would be really great if the www translations would be available in the SVN, like the program translations.

**Comment by bdoin** [comment]
Thanks, I merged your patch and pushed it to gcompris.net. We moving to svn is in our todo list.
